language: android

android:
  components:
    - build-tools-28.0.3
    - android-28

jobs:
  include:
    - stage: checkLint
      language: android
      before_script: chmod +x gradlew
      script: ./gradlew ktlint

    - stage: compile
      language: android
      before_script: chmod +x gradlew
      script: ./gradlew clean assembleDebug assembleRelease

    - stage: tests
      language: android
      before_script: chmod +x gradlew
      script: ./gradlew runUnitTests
