language: android

android:
  components:
    - build-tools-28.0.3
    - android-28

jobs:
  include:
    - stage: compile
      language: android
      before_script: chmod +x gradlew
      script:
        - ./gradlew ktlint
        - ./gradlew assembleDebug

    - stage: tests
      language: android
      before_script: chmod +x gradlew
      script: 
        - ls
        - ./gradlew jacocoTestReport
        - cd TRAVIS_BUILD_DIR/displayJacoco/dist/
        - ./output_jacoco_metrics.exe
